### ISSUE TITLE
Do you plan to add minification to the plugin default config?

### ISSUE THREAD

**Issue by oupala** [alex-ketch/metalsmith-purifycss#4]
Do you plan to add minification to the plugin default config?

Or do you plan to make the parameter available so that it is possible to minify a file along with purification?

source: see [documentation of PurifiCSS](https://github.com/purifycss/purifycss#properties-of-options-object)

**Comment by alex-ketch** [comment]
Hey @oupala, I'll try and and update this plugin to pass through the options to the plugin sometime this weekend. Honestly though I don't use Metalsmith any more, and have not been keeping this plugin up to date.

**Comment by oupala** [comment]
Thanks for doing it, if you can.

**Comment by alex-ketch** [comment]
Hey @oupala, just took a look at the project, and looks like all the options should be getting passed along to PurifyCSS. Does setting the `minify` option not work for you?

https://github.com/alex-ketch/metalsmith-purifycss/blob/9f527093c45f01c6935098a0bbc4713ce5f53f5e/lib/index.js#L36

**Comment by oupala** [comment]
You're right, all the options from PurifyCSS are available as options to metalsmith-purifycss. The only thing that could be improved is the documentation to tell that all the options from PurifyCSS are available as options to metalsmith-purifycss.

Thanks @alex-ketch for your answer.
